name: Maven Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Maven debug mode
        required: false
        default: false
      ssh:
        type: boolean
        description: Open SSH session in the runner
        required: false
        default: false
      uploadCheckstyleReport:
        type: string
        description: "Enable the upload of any Checkstyle report created by Maven"
        default: "false"
      uploadPMDReport:
        type: string
        description: "Enable the upload of any PMD report created by Maven"
        default: "false"
      uploadSpotbugsReport:
        type: string
        description: "Enable the upload of any Spotbugs report created by Maven"
        default: "false"


jobs:
  build:
    uses: metricshub/workflows/.github/workflows/maven-build.yml@v4
    with:
      jdkVersion: "17"
      debug: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
      ssh: ${{ github.event_name == 'workflow_dispatch' && inputs.ssh }}
